#!/bin/bash
# usage: an_round_report.sh <run_id> [playerbots.log]
R=$1; LOG=${2:-/Users/nowcoder/IdeaProjects/github/wow335/azerothcore-wotlk/Playerbots.log}
M="/opt/homebrew/bin/mysql -uacore -pacore -N acore_characters"
echo "===== attempts run $R"; $M -e "SELECT seq,result,duration_ms,deaths,boss_hp_min FROM raidtest_attempts WHERE run_id=$R ORDER BY seq;" 2>/dev/null
echo "===== alive falls (z<200 before death)"; $M -e "
SELECT f.seq, f.bot, f.fall_t, IFNULL(d.death_t,'alive') FROM (
 SELECT a.seq, a.id aid, e.source_guid bot, ROUND(MIN(e.rel_ms)/1000) fall_t FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id
 WHERE a.run_id=$R AND e.event_type='state' AND e.detail LIKE 'pos:%' AND e.source_guid BETWEEN 796 AND 800 AND CAST(SUBSTRING_INDEX(e.detail,',',-1) AS DECIMAL(10,2))<200 GROUP BY a.seq,a.id,e.source_guid) f
LEFT JOIN (SELECT attempt_id, source_guid, ROUND(MIN(rel_ms)/1000) death_t FROM raidtest_events WHERE event_type='death' GROUP BY attempt_id, source_guid) d ON d.attempt_id=f.aid AND d.source_guid=f.bot
WHERE d.death_t IS NULL OR f.fall_t < d.death_t ORDER BY f.seq;" 2>/dev/null | awk '{printf "seq%s bot=%s fell=%ss death=%s | ",$1,$2,$3,$4} END{print ""}'
echo "===== boss hits >=15000 on players (died within 3s?)"; $M -e "SELECT a.seq, ROUND(e.rel_ms/1000), e.target_guid, e.value, EXISTS(SELECT 1 FROM raidtest_events d WHERE d.attempt_id=e.attempt_id AND d.event_type='death' AND d.source_guid=e.target_guid AND d.rel_ms BETWEEN e.rel_ms-500 AND e.rel_ms+3000) FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='damage' AND e.source_guid=104 AND e.target_guid BETWEEN 796 AND 800 AND e.value>=15000 ORDER BY a.seq, e.rel_ms;" 2>/dev/null | awk '{printf "seq%s t=%ss v=%s hit=%s died=%s | ",$1,$2,$3,$4,$5} END{print ""}'
echo "===== ranged (799,800) distance to tank, 4-yd bins"; $M -e "
SELECT r.source_guid, FLOOR(SQRT(POW(r.x-t.x,2)+POW(r.y-t.y,2))/4)*4 db, COUNT(*) FROM
 (SELECT e.attempt_id, e.rel_ms, e.source_guid, CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,':',-1),',',1) AS DECIMAL(10,2)) x, CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,',',2),',',-1) AS DECIMAL(10,2)) y FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='state' AND e.detail LIKE 'pos:%' AND e.source_guid IN (799,800) AND CAST(SUBSTRING_INDEX(e.detail,',',-1) AS DECIMAL(10,2))>=223) r
 JOIN (SELECT e.attempt_id, e.rel_ms, CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,':',-1),',',1) AS DECIMAL(10,2)) x, CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,',',2),',',-1) AS DECIMAL(10,2)) y FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='state' AND e.detail LIKE 'pos:%' AND e.source_guid=796) t
 ON t.attempt_id=r.attempt_id AND t.rel_ms=r.rel_ms GROUP BY r.source_guid, db ORDER BY r.source_guid, db;" 2>/dev/null | awk '{printf "%s:%s=%s ",$1,$2,$3} END{print ""}'
echo "===== ranged x distribution (3-yd bins, z>=223)"; $M -e "SELECT FLOOR(CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,':',-1),',',1) AS DECIMAL(10,2))/3)*3 xb, COUNT(*) FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='state' AND e.detail LIKE 'pos:%' AND e.source_guid IN (797,799,800) AND CAST(SUBSTRING_INDEX(e.detail,',',-1) AS DECIMAL(10,2))>=223 GROUP BY xb ORDER BY xb;" 2>/dev/null | tr '\n' ' '; echo
echo "===== new action outcomes (log)"; grep -o "Raidte[a-e]nfivc A:anub'arak \(rim guard\|keep range\|dodge pound\|dodge impale\) - [A-Z]*" "$LOG" | sed -E 's/Raidte(.)nfivc/\1/' | sort | uniq -c | sort -k2
echo "===== mage casts per attempt (LB 55360, fireball 42833, blizzard 42940, flamestrike 42926, potion 43186)"; $M -e "SELECT a.seq, e.spell_id, COUNT(*) FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='spell' AND e.source_guid=799 AND e.spell_id IN (55360,42833,42940,42926,43186) GROUP BY a.seq, e.spell_id ORDER BY a.seq, e.spell_id;" 2>/dev/null | awk '{k=$1; if(k!=prev){printf "\nseq%s:",k; prev=k} printf " %s×%s",$2,$3} END{print ""}'
for g in 797 799; do echo "===== mana min per 30s guid $g"; $M -e "SELECT a.seq, FLOOR(e.rel_ms/30000)*30 t, MIN(CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(e.detail,'power=',-1),'/',1) AS UNSIGNED)) FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='state' AND e.source_guid=$g AND e.detail LIKE 'resource:%' GROUP BY a.seq,t ORDER BY a.seq,t;" 2>/dev/null | awk '{k=$1; if(k!=prev){printf "\nseq%s:",k; prev=k} printf " %s=%s",$2,$3} END{print ""}'; done
echo "===== deaths"; $M -e "SELECT a.seq, ROUND(e.rel_ms/1000), e.source_guid FROM raidtest_events e JOIN raidtest_attempts a ON a.id=e.attempt_id WHERE a.run_id=$R AND e.event_type='death' ORDER BY a.seq, e.rel_ms;" 2>/dev/null | awk '{printf "seq%s t=%ss v=%s | ",$1,$2,$3} END{print ""}'
